### ISSUE TITLE
Screen swiping for console error reporting

### ISSUE THREAD

**Issue by yuyuko233** [Multitallented/Civs#101]
Screen swiping for console error reporting.
Here is the error report
`Error occurred during Civs heartbeat player check
java.lang.NullPointerException: null
at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.incrementMana(CommonScheduler.java:131) ~[?:?]
at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.checkPlayer(CommonScheduler.java:84) ~[?:?]
at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.run(CommonScheduler.java:61) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[PaperSpigot-1.15.2.jar:git-Paper-145]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[PaperSpigot-1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[PaperSpigot-1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[PaperSpigot-1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[PaperSpigot-1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[PaperSpigot-1.15.2.jar:git-Paper-145]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]`

**Comment by Multitallented** [comment]
Should be fixed in v1.6.6
