### ISSUE TITLE
Error occurred while enabling Civs v1.6.5 (Is it up to date?)

### ISSUE THREAD

**Issue by phx175** [Multitallented/Civs#102]
Hi.

Just found this and love the idea. When starting the server I have the following errors:
java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.filterInputsBy(Lcom/google/common/base/Predicate;)Lorg/reflections/util/ConfigurationBuilder;
	at org.redcastlemedia.multitallented.civs.Civs.instantiateSingletons(Civs.java:207) ~[?:?]
	at org.redcastlemedia.multitallented.civs.Civs.onEnable(Civs.java:65) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-a03b1fd-95bd423]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot.jar:git-Spigot-a03b1fd-95bd423]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot.jar:git-Spigot-a03b1fd-95bd423]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot.jar:git-Spigot-a03b1fd-95bd423]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot.jar:git-Spigot-a03b1fd-95bd423]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot.jar:git-Spigot-a03b1fd-95bd423]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot.jar:git-Spigot-a03b1fd-95bd423]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot.jar:git-Spigot-a03b1fd-95bd423]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

Entering /cv leads to 

[Civs] Invalid command menu

Please advise. Many thanks in advance!

**Comment by Multitallented** [comment]
One of your other plugins is using an outdated version of the reflections library. Whatever plugin that is will cause Civs to crash like you see here. Either remove that plugin, or get the developer to update his/her reflections library.
