### ISSUE TITLE
Town Members aren't listed at all.

### ISSUE THREAD

**Issue by MothGirlMusic** [Multitallented/Civs#142]
The only error in the console is this one:
```
[15:10:32] [Server thread/ERROR]: Exception thrown during inventory click
java.lang.IllegalArgumentException: Invalid UUID string: $uuid$
	at java.util.UUID.fromString(UUID.java:194) ~[?:1.8.0_252]
	at org.redcastlemedia.multitallented.civs.menus.towns.SelectTownMenu.createData(SelectTownMenu.java:34) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.CustomMenu.createMenu(CustomMenu.java:54) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.MenuManager.openMenu(MenuManager.java:260) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.MenuManager.openMenuFromString(MenuManager.java:286) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.CustomMenu.doActionAndCancel(CustomMenu.java:219) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.CustomMenu.onInventoryClick(CustomMenu.java:189) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.MenuManager.onInventoryClick(MenuManager.java:141) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor833.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-2f5d615-d07a78b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-2f5d615-d07a78b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-2f5d615-d07a78b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2148) ~[server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [server.jar:git-Spigot-2f5d615-d07a78b]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [server.jar:git-Spigot-2f5d615-d07a78b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[15:10:33] [Server thread/ERROR]: Unable to find any translation for potato_farm1-name
[15:10:38] [Server thread/ERROR]: Unable to find any translation for potato_farm1-name
```
Howerver, for some reason, no players are populated in the list when viewing them. as well, when players are added to a town via command, it works. but they don't seem to be added to any of the regions within that town. it seems that must be done manually and seems to be from the same issue. back a while ago when it was working fine and people were being listed, it worked as such and you could add someone to your town and have them added to all regions within that town. now it seems like you need to manually add them to all regions yourself since the menu doesn't seem to populate.

images:
![Bildschirmfoto 2020-05-25 um 17 00 26](https://user-images.githubusercontent.com/1746550/82843147-45bf1100-9eaa-11ea-8bba-9aacc911ef1c.png)
![Bildschirmfoto 2020-05-25 um 17 00 34](https://user-images.githubusercontent.com/1746550/82843148-4657a780-9eaa-11ea-8a34-854c0b9c1d7f.png)

**Comment by wayspurrchen** [comment]
+1, I am also seeing this issue on my 1.17.1 server.
