### ISSUE TITLE
1.16.5  chat error.

### ISSUE THREAD

**Issue by Chypik** [Multitallented/Civs#195]
I write through translator.
if 1 player writes to the chat, then simply writes that there are no players.
But if the players are still on the server, then this error will be sent to the console, there is nothing in the game chat.

This server is running Paper version git-Paper-592 (MC: 1.16.5)
plugins:
Civs v1.9.1

```
[15:57:19] [Async Chat Thread - #2/ERROR]: Could not pass event AsyncPlayerChatEvent to Civs v1.9.1
java.lang.NoClassDefFoundError: org/redcastlemedia/multitallented/civs/placeholderexpansion/PlaceHook
	at org.redcastlemedia.multitallented.civs.chat.ChatManager.formatMessage(ChatManager.java:56) ~[?:?]
	at org.redcastlemedia.multitallented.civs.civilians.CivilianListener.onPlayerChat(CivilianListener.java:723) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor69.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-592]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-592]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:224) ~[patched_1.16.5.jar:git-Paper-592]
	at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:104) ~[patched_1.16.5.jar:git-Paper-592]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:62) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2085) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1938) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:44) ~[patched_1.16.5.jar:git-Paper-592]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by Chypik** [comment]
Решение:  Civs v1.9.2
