### ISSUE TITLE
Error in console when clicking user head in main menu

### ISSUE THREAD

**Issue by WickedSik** [Multitallented/Civs#196]
Version: 1.9.2

This happened when I opened the menu from the starter book, and clicked on my own player head in the top right corner. The menu closed after this.

```
[13:46:37 ERROR]: Exception while opening the menu
java.lang.IllegalArgumentException: Invalid UUID string: $uuid$
	at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.people.PlayerMenu.createData(PlayerMenu.java:36) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.CustomMenu.createMenu(CustomMenu.java:63) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.MenuManager.openMenu(MenuManager.java:319) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.MenuManager.openMenuFromString(MenuManager.java:350) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.CustomMenu.doActionAndCancel(CustomMenu.java:255) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.CustomMenu.onInventoryClick(CustomMenu.java:225) ~[?:?]
	at org.redcastlemedia.multitallented.civs.menus.MenuManager.onInventoryClick(MenuManager.java:145) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor103.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-603]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-603]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-603]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2700) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-603]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-603]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

I do not know what is behind this icon, maybe there is nothing? It's not a big bug to me.

**Comment by vyvin** [comment]
Getting this myself, but only when inside a region, outside of regions it works fine
