### ISSUE TITLE
First of all,thank you to build this interesting plugins

### ISSUE THREAD

**Issue by 2489742701** [Multitallented/Civs#220]
A strange problem, my player can put the coal store directly on the ground without following the guide prompts to place the prerequisite blocks, and it shows that the establishment is successful. At this time, the guide will not instruct the player what to do next, but in the The quest for the coal store is paused. The latest version of the plugin is used, and the server version is 1.17.1

**Comment by Multitallented** [comment]
Did your get any errors in the log?

**Comment by 2489742701** [comment]
too many! some about translate and some about the Couldn't look up profile properties

Players can directly buy and place equipment without building requirements, the building requirements in the plugin's gui menu are empty, and nothing will be displayed after opening


风分钟 12:25:09
[12:23:31 INFO]: shenfengtianmie[/112.22.164.14:7616] logged in with entity id 4407 at ([world]1581.2007012231327, 71.875, 314.57948339815596)
[12:23:33 ERROR]: Unable to find any translation for payout-money
[12:23:33 ERROR]: Unable to find any translation for payout-money
[12:23:33 ERROR]: Unable to find any translation for payout-money
[12:23:33 ERROR]: Unable to find any translation for payout-money
[12:23:39 INFO]: [AuthMe] shenfengtianmie logged in 112.22.164.14
[12:23:39 ERROR]: Unable to find any translation for payout-money
[12:23:39 ERROR]: Unable to find any translation for payout-money
[12:23:39 ERROR]: Unable to find any translation for payout-money
[12:23:39 ERROR]: Unable to find any translation for payout-money
[12:23:40 ERROR]: Unable to find any translation for coords
[12:23:40 ERROR]: Unable to find any translation for region-cooldown
[12:23:43 ERROR]: Unable to find any translation for concrete_factory-name
[12:23:47 ERROR]: Unable to find any translation for amethyst_mine-name
[12:23:47 ERROR]: Unable to find any translation for amethyst_mine-desc
[12:23:47 ERROR]: Unable to find any translation for amethyst_mine-name
[12:23:47 ERROR]: Unable to find any translation for amethyst_mine-desc
[12:23:47 ERROR]: Unable to find any translation for copper_mine-name
[12:23:47 ERROR]: Unable to find any translation for copper_mine-desc
[12:23:47 ERROR]: Unable to find any translation for copper_mine-name
[12:23:47 ERROR]: Unable to find any translation for copper_mine-desc
[12:23:47 ERROR]: Unable to find any translation for netherite_mine-name
[12:23:47 ERROR]: Unable to find any translation for netherite_mine-desc
[12:23:47 ERROR]: Unable to find any translation for netherite_mine-name
[12:23:47 ERROR]: Unable to find any translation for netherite_mine-desc
[12:23:48 ERROR]: Unable to find any translation for time-minutes
[12:23:48 ERROR]: Unable to find any translation for coords
[12:23:48 ERROR]: Unable to find any translation for region-cooldown
[12:23:50 ERROR]: Unable to find any translation for time-minutes
[12:23:50 ERROR]: Unable to find any translation for coords
[12:23:50 ERROR]: Unable to find any translation for region-cooldown

风分钟 12:25:23
[12:23:57 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@31ac813a[id=b37d428d-acb6-399b-aa87-2b17728cbfd4,name=5454_axe,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:124) ~[sever.jar:3284a-Spigot-3892929-0ab8487]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:98) ~[sever.jar:3284a-Spigot-3892929-0ab8487]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:193) ~[sever.jar:3284a-Spigot-3892929-0ab8487]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[sever.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.level.block.entity.TileEntitySkull.c(SourceFile:144) ~[sever.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.SystemUtils.a(SourceFile:448) ~[sever.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.world.level.block.entity.TileEntitySkull.a(SourceFile:139) ~[sever.jar:3284a-Spigot-3892929-0ab8487]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1460) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064) ~[?:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:825) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:760) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:140) ~[sever.jar:3284a-Spigot-3892929-0ab8487]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:103) ~[sever.jar:3284a-Spigot-3892929-0ab8487]
	... 12 more

**Comment by 2489742701** [comment]
I seem to understand, some devices have a price of 0, players can buy directly but can't use it, is it because these devices have not been unlocked? Players need to upgrade to use? is that so

**Comment by 2489742701** [comment]
This is very uncomfortable. A large number of machines in the store are worth 0

They can't be used, but they can be placed without prompting the construction needs

I may need help
