### ISSUE TITLE
Error with no money but I have Vault and 2 other economy system

### ISSUE THREAD

**Issue by Guilefilou** [Multitallented/Civs#228]
hello,
I don't know why CIVS don't want take money of Vault. I have this error:

<html>
<body>

[14:40:51] [Server thread/ERROR]: Unable to find any translation for barracks1-name
--
4992 | [14:40:51] [Server thread/ERROR]: Unable to find any translation for barracks1-desc
4993 | [14:40:51] [Server thread/ERROR]: Unable to find any translation for barracks1-name
4994 | [14:40:51] [Server thread/ERROR]: Unable to find any translation for barracks1-desc
4995 | [14:40:51] [Server thread/ERROR]: Unable to find any translation for inn1-name
4996 | [14:40:51] [Server thread/ERROR]: Unable to find any translation for inn1-desc
4997 | [14:40:51] [Server thread/ERROR]: Unable to find any translation for inn1-name
4998 | [14:40:51] [Server thread/ERROR]: Unable to find any translation for inn1-desc
4999 | [14:40:58] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Civs v1.11.1
5000 | org.bukkit.event.EventException: null
5001 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5002 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5003 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5004 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5005 | at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2436) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5006 | at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5007 | at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5008 | at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5009 | at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5010 | at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5011 | at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5012 | at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5013 | at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5014 | at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5015 | at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5016 | at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5017 | at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5018 | at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5019 | at java.lang.Thread.run(Thread.java:831) [?:?]
5020 | Caused by: java.lang.NoSuchFieldError: DIRT_PATH
5021 | at org.redcastlemedia.multitallented.civs.regions.StructureUtil.setGlass(StructureUtil.java:229) ~[?:?]
5022 | at org.redcastlemedia.multitallented.civs.regions.StructureUtil.showGuideBoundingBox(StructureUtil.java:129) ~[?:?]
5023 | at org.redcastlemedia.multitallented.civs.regions.StructureUtil.showGuideBoundingBox(StructureUtil.java:86) ~[?:?]
5024 | at org.redcastlemedia.multitallented.civs.menus.regions.RegionTypeMenu.createData(RegionTypeMenu.java:60) ~[?:?]
5025 | at org.redcastlemedia.multitallented.civs.menus.CustomMenu.createMenu(CustomMenu.java:64) ~[?:?]
5026 | at org.redcastlemedia.multitallented.civs.menus.MenuManager.openMenu(MenuManager.java:319) ~[?:?]
5027 | at org.redcastlemedia.multitallented.civs.menus.common.ShopMenu.doActionAndCancel(ShopMenu.java:187) ~[?:?]
5028 | at org.redcastlemedia.multitallented.civs.menus.CustomMenu.onInventoryClick(CustomMenu.java:237) ~[?:?]
5029 | at org.redcastlemedia.multitallented.civs.menus.MenuManager.onInventoryClick(MenuManager.java:145) ~[?:?]
5030 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
5031 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
5032 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
5033 | at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
5034 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5035 | ... 18 more
5036 | [14:41:07] [Server thread/ERROR]: Unable to find any translation for inn1-name
5037 | [14:41:07] [Server thread/ERROR]: Unable to find any translation for inn1-desc
5038 | [14:41:17] [Server thread/ERROR]: Unable to find any translation for barracks1-name
5039 | [14:41:17] [Server thread/ERROR]: Unable to find any translation for barracks1-desc
5040 | [14:41:17] [Server thread/ERROR]: Unable to find any translation for barracks1-name
5041 | [14:41:17] [Server thread/ERROR]: Unable to find any translation for barracks1-desc
5042 | [14:41:17] [Server thread/ERROR]: Unable to find any translation for inn1-name
5043 | [14:41:17] [Server thread/ERROR]: Unable to find any translation for inn1-desc
5044 | [14:41:17] [Server thread/ERROR]: Unable to find any translation for inn1-name
5045 | [14:41:17] [Server thread/ERROR]: Unable to find any translation for inn1-desc
5046 | [14:41:23] [Server thread/ERROR]: Unable to find any translation for barracks1-name
5047 | [14:41:23] [Server thread/ERROR]: Unable to find any translation for barracks1-desc
5048 | [14:41:23] [Server thread/ERROR]: Unable to find any translation for barracks1-name
5049 | [14:41:23] [Server thread/ERROR]: Unable to find any translation for barracks1-desc
5050 | [14:41:40] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Civs v1.11.1
5051 | org.bukkit.event.EventException: null
5052 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5053 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5054 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5055 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5056 | at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2436) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5057 | at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5058 | at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5059 | at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5060 | at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5061 | at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5062 | at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5063 | at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5064 | at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5065 | at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5066 | at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5067 | at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5068 | at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5069 | at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5070 | at java.lang.Thread.run(Thread.java:831) [?:?]
5071 | Caused by: java.lang.NoSuchFieldError: DIRT_PATH
5072 | at org.redcastlemedia.multitallented.civs.regions.StructureUtil.setGlass(StructureUtil.java:229) ~[?:?]
5073 | at org.redcastlemedia.multitallented.civs.regions.StructureUtil.showGuideBoundingBox(StructureUtil.java:129) ~[?:?]
5074 | at org.redcastlemedia.multitallented.civs.regions.StructureUtil.showGuideBoundingBox(StructureUtil.java:86) ~[?:?]
5075 | at org.redcastlemedia.multitallented.civs.menus.regions.RegionTypeMenu.createData(RegionTypeMenu.java:60) ~[?:?]
5076 | at org.redcastlemedia.multitallented.civs.menus.CustomMenu.createMenu(CustomMenu.java:64) ~[?:?]
5077 | at org.redcastlemedia.multitallented.civs.menus.MenuManager.openMenu(MenuManager.java:319) ~[?:?]
5078 | at org.redcastlemedia.multitallented.civs.menus.common.ShopMenu.doActionAndCancel(ShopMenu.java:187) ~[?:?]
5079 | at org.redcastlemedia.multitallented.civs.menus.CustomMenu.onInventoryClick(CustomMenu.java:237) ~[?:?]
5080 | at org.redcastlemedia.multitallented.civs.menus.MenuManager.onInventoryClick(MenuManager.java:145) ~[?:?]
5081 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
5082 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
5083 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
5084 | at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
5085 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:3096-Spigot-9fb885e-296df56]
5086 | ... 18 more

</body>
</html>

PLZ HELP ME I WANT PLAY WITH MY FRIEND WITH THIS PLUGIN!!!
thx

**Comment by Guilefilou** [comment]
i demand to chat gpt to solve the problem and he found:

"The error is caused by a NoSuchFieldError in the Civs plugin, specifically in the StructureUtil class. The field that is being accessed (DIRTPATH) does not exist, leading to the error.

To resolve the issue, the plugin developers should review the code in the StructureUtil class and determine if the field is necessary or if it can be removed. They should also ensure that all dependencies are properly installed and up to date. Alternatively, the plugin users can try contacting the developers for a fix or update to the plugin."
