### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nikissXI** [Multitallented/Civs#92]
[14:37:54 ERROR]: Could not pass event BlockBreakEvent to Civs v1.6.5
java.lang.NullPointerException: null
at org.redcastlemedia.multitallented.civs.items.ItemManager.getItemType(ItemManager.java:417) ~[?:?]
at org.redcastlemedia.multitallented.civs.menus.common.RecipeMenu.createItemStack(RecipeMenu.java:95) ~[?:?]
at org.redcastlemedia.multitallented.civs.menus.CustomMenu.createMenu(CustomMenu.java:71) ~[?:?]
at org.redcastlemedia.multitallented.civs.menus.CustomMenu.createMenuFromHistory(CustomMenu.java:58) ~[?:?]
at org.redcastlemedia.multitallented.civs.menus.MenuManager.openMenuFromHistory(MenuManager.java:233) ~[?:?]
at org.redcastlemedia.multitallented.civs.protections.ProtectionHandler.onBlockBreak(ProtectionHandler.java:143) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-122]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-122]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-122]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:313) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:272) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:240) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1320) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-122]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by LoJoSho** [comment]
I think this was answered in discord, however, not on GitHub.

More information is required. However, some plugins that add new items have been known to conflict with Civs, including [Custom Items](https://www.mc-market.org/resources/10728/). The only plugin that has so far been integrated to work fully with Civs is with MMOItems via MMOLib.

**Comment by Multitallented** [comment]
I believe this issue is the result of an item being present in game, but removed from the configs. If you have more information then I can fix it. Please reopen this ticket when you have more information about what you did with your configs.
